### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by thedarkjester** [jccalderon/blockchain-developer-bootcamp-final-project#1]
was looking to mark your project but the screencast isn't available
![image](https://user-images.githubusercontent.com/3957173/151673380-a696603a-5cd7-4570-989e-45c8d1672969.png)

**Comment by jccalderon** [comment]
Sorry, the video was set to private. It is now set to public

**Comment by thedarkjester** [comment]
thanks - all viewed
